### ISSUE TITLE
Add links to "usefull tools"

### ISSUE THREAD

**Issue by rebmema** [ydeverdiere/ydeverdiere.github.io#8]
Maybe it could be usefull to provide more informations on the tools listed on the GDB cheatsheet.
Like a link related man page, or website.

**Comment by ydeverdiere** [comment]
Yes, it is a work to do :)
It was the original idea, but I prefered to publish something about GDB.
But if you want to do something about this?

**Comment by rebmema** [comment]
This should be within my capabilities !

**Comment by ydeverdiere** [comment]
Ok
